runtime: python
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

api_version: 1
threadsafe: true
handlers:
- url: /(.*\.(ico$|jpg$|png$|gif$|wav$|html$|html5$|))

manual_scaling:
  instances: 1